ALTER TABLE songs ADD COLUMN IF NOT EXISTS lyrics TEXT DEFAULT '';
ALTER TABLE songs ADD COLUMN IF NOT EXISTS default_time_signature TEXT DEFAULT '4/4';
ALTER TABLE songs ADD COLUMN IF NOT EXISTS default_key TEXT DEFAULT 'G';
ALTER TABLE songs ADD COLUMN IF NOT EXISTS default_bpm INTEGER DEFAULT 120;

ALTER TABLE setlist_sections ADD COLUMN IF NOT EXISTS song_key TEXT DEFAULT NULL;
ALTER TABLE setlist_sections ADD COLUMN IF NOT EXISTS override_lyrics TEXT DEFAULT NULL;

ALTER TABLE songs ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft';
ALTER TABLE songs ADD COLUMN IF NOT EXISTS chords TEXT DEFAULT NULL;
