ALTER TABLE songs ADD COLUMN IF NOT EXISTS lyrics TEXT DEFAULT '';
ALTER TABLE songs ADD COLUMN IF NOT EXISTS default_time_signature TEXT DEFAULT '4/4';
ALTER TABLE songs ADD COLUMN IF NOT EXISTS default_key TEXT DEFAULT 'G';
ALTER TABLE songs ADD COLUMN IF NOT EXISTS default_bpm INTEGER DEFAULT 120;
